name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      TF_WORKSPACE: dev 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Initialize Terraform
        run: terraform init

      - name: Select workspace (or create if it doesn't exist)
        run: |
          terraform workspace list | grep -q "${TF_WORKSPACE}" \
            && terraform workspace select "${TF_WORKSPACE}" \
            || terraform workspace new "${TF_WORKSPACE}"

      - name: Terraform Plan
        run: terraform plan -no-color
